version: '2'
services:

  testrpc:
    image: dougvk/testrpc:latest
    env_file:
      - ./environment.env
    ports:
      - "8545:8545"
    command: bash -c "testrpc -h 0.0.0.0 -m 'divert spare attend review reveal satisfy diagram type afraid annual swim style'"
  
  ipfs:
    build: ./ipfs
    ports:
     - "8080:8080"
     - "5001:5001"
     - "4001:4001"
    #  Uncomment this if you want to persist your IPFS data locally
    #  Otherwise it will always be a new instance (no persistence)
    # volumes:
    #   - ~/.ipfs/:/data/ipfs/

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./environment.env
    ports:
      - "3001:3001"
    links:
      - testrpc

  dapp:
    build:
      context: ./dapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
     - ./dapp/src:/usr/src/app/src
    links:
     - ipfs
     - testrpc
     - server