version: '2'
services:
  testrpc:
    image: dougvk/testrpc:latest
    ports:
      - "8545:8545"
    command: bash -c "testrpc -h 0.0.0.0"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/server.env
    ports:
      - "8080:8080"
    links:
      - testrpc